cloud:
  aws:
    credentials:
      access-key: AKIAZKLSP3C4CPIV6JAR
      secret-key: 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
    region:
      static: us-east-1
    stack:
      auto: false

application:
  bucket:
    name: farm-stead