cloud:
  aws:
    credentials:
      access-key: AKIAZKLSP3C4KW55KGNW
      secret-key: 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
    region:
      static: us-east-1
    stack:
      auto: false

application:
  bucket:
    name: farm-stead